In [3]:
import numpy as np

In [ ]:
# multiply two matrices


a = np.ones((5,4)
            )
print(a)

b = np.full((4,2), 3)

print(b)

print(np.matmul(a,b))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]]
[[12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]]


In [17]:
# find determinant of a matrix
c = np.array([[1, 4],[4,2]])
det = np.linalg.det(c)
print(det)

-14.000000000000004


In [22]:
d= np.ones([5,5])
print(d)
print(np.linalg.det(d))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
0.0


In [25]:
e = np.identity(5)
print(e)
print(np.linalg.det(e))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
1.0
