In [2]:
print("hi")

hi


In [3]:
print("Hello World")

Hello World


In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])

In [7]:
print(arr1)

[1 2 3 4 5]


In [11]:
arrd = np.array([[1,2,3],[4,5,6]])
print(arrd)

[[1 2 3]
 [4 5 6]]


In [12]:
arrdd= np.single([1,2,3,4,5])
print(arrdd)

[1. 2. 3. 4. 5.]


In [16]:
arrdd = np.identity(5)
print(arrdd)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
ones = np.ones((7,6))


In [18]:
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
np.multiply(ones,2)

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [20]:
np.multiply(arr1,arrdd)

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [21]:
print(arr1.ndim)

1


In [22]:
arr1.ndim

1

In [24]:
arrs = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arrs.ndim)

3


In [26]:
arrs.shape
arrs

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arrs.shape

(2, 2, 3)

In [33]:
# get element in array (r, c)
arrs[1,1]

array([10, 11, 12])

In [36]:
# get specific row
arrs[1, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [40]:
a[0,5] = 100
a

array([[  1,   2,   3,   4,   5, 100,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15, 100,  17,  18,  19,  20]])

In [41]:
a.shape

(2, 10)

In [42]:
a.size

20

In [47]:
a[0, :7]

array([  1,   2,   3,   4,   5, 100,   7])

In [48]:
a[1, :3]

array([11, 12, 13])

In [ ]:
a[1, 1:4]
# [startindex:endindex:stepsize]
# startindex is inclusive and endindex is exclusive

array([12, 13, 14])

In [83]:
# 3d array
a3 = np.array(
  [
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
  ]
)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [58]:
# get element in array (r, c, d)
print(a3[1,1,1])

11


In [61]:
print(a3[0,1,1])

5


In [68]:
print(a3[1,0,2])

9


In [69]:
a3[1,1,2] = 100
print(a3)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11 100]]]


In [82]:
a3[1,0] = [1,2,3]
print(a3)

[[[1 2 3]
  [9 9 9]]

 [[1 2 3]
  [8 8 8]]]


In [81]:
a3[1] = [[9,9,9], [8,8,8]]
a3

array([[[1, 2, 3],
        [9, 9, 9]],

       [[9, 9, 9],
        [8, 8, 8]]])