In [2]:
import numpy as np

In [4]:
before = np.array([[1, 2, 3], [7, 8, 9]])

In [15]:
print(before)
print(before.shape)

[[1 2 3]
 [7 8 9]]
(2, 3)


In [17]:
after = before.reshape((3,2))
print(after)
print(after.shape)

[[1 2]
 [3 7]
 [8 9]]
(3, 2)


In [27]:
# vertical stacking
m1 = np.array([
  [1,2,3],
  [4,5,6]
])

m2 = np.array([
  [3,2,1],
  [6,5,4]
])

print(m1)
print(m2)

vstacked  = np.vstack([m1,m2])
print(vstacked)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]


In [29]:
# horizontal stacking

hstacked = np.hstack((m1, m2))
print(hstacked)

[[1 2 3 3 2 1]
 [4 5 6 6 5 4]]


In [19]:

# read file 
file =(np.genfromtxt("data.txt", delimiter=","))
print(file)

[[  1.  23.  35.  46. 567. 236.   7.   8.   8.  11. 213. 532. 234.   2.
   23. 234.]
 [  1.  23.  35.  46. 567. 236.   7.   8.   8.  11. 213. 532. 234.   2.
   23.   2.]
 [  1.  23.  35.  46. 567. 236.   7.   8.   8.  11. 213. 532. 234.   2.
   23. 234.]]


In [20]:
print(file.astype("int32"))

[[  1  23  35  46 567 236   7   8   8  11 213 532 234   2  23 234]
 [  1  23  35  46 567 236   7   8   8  11 213 532 234   2  23   2]
 [  1  23  35  46 567 236   7   8   8  11 213 532 234   2  23 234]]


In [38]:
# boolen masking and advanced indexing
f = file <= 7
print(f)

e = file[file <= 9]
print(e)

[[ True False False False False False  True False False False False False
  False  True False False]
 [ True False False False False False  True False False False False False
  False  True False  True]
 [ True False False False False False  True False False False False False
  False  True False False]]
[1. 7. 8. 8. 2. 1. 7. 8. 8. 2. 2. 1. 7. 8. 8. 2.]


In [ ]:
# get elemnet by index

print(e[[1]])
print(e[[5,6]])

[7.]
[1. 7.]


In [48]:
print(np.all(f >= 2))

False


In [49]:
eg = np.array([
  [1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15],
  [16,17,18,19,20],
  [21,22,23,24,25],
  [26,27,28,29,30]
])

print(eg)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [68]:
print(eg[2:4,0:2])

[[11 12]
 [16 17]]


In [75]:
# get elements at specific indices
# first array is row indices and second array is column indices

eg[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [84]:
eg[
  [0,4,5], 3:5
  ]

array([[ 4,  5],
       [24, 25],
       [29, 30]])