In [1]:
import numpy as np

In [4]:
before = np.array([[1, 2, 3], [7, 8, 9]])

In [15]:
print(before)
print(before.shape)

[[1 2 3]
 [7 8 9]]
(2, 3)


In [17]:
after = before.reshape((3,2))
print(after)
print(after.shape)

[[1 2]
 [3 7]
 [8 9]]
(3, 2)


In [27]:
# vertical stacking
m1 = np.array([
  [1,2,3],
  [4,5,6]
])

m2 = np.array([
  [3,2,1],
  [6,5,4]
])

print(m1)
print(m2)

vstacked  = np.vstack([m1,m2])
print(vstacked)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]


In [29]:
# horizontal stacking

hstacked = np.hstack((m1, m2))
print(hstacked)

[[1 2 3 3 2 1]
 [4 5 6 6 5 4]]
