In [1]:
import numpy as np

In [11]:
# find min

stats = np.array([
  [1,2,3],
  [4,5,6],
  [8,8,9]
])

# print(stats.shape)
# print(stats)
print(np.min(stats, axis=1))

[1 4 8]


In [15]:
#print max
print(np.max(stats, axis =1))
print(np.max(stats, axis =0))

[3 6 9]
[8 8 9]


In [19]:
# sum
print(np.sum(stats))
print(np.sum(stats, axis = 1))
print(np.sum(stats, axis = 0))

46
[ 6 15 25]
[13 15 18]
